/* Array of all the notes */
const scales = [
    {
        id: 1,
        name: "Major",
        slug: "major",
        formula: [
            {
                id: 1,
                chromatic: 1,
                degree: "1",
                mode: "Ionian (Major)",
                chord: "maj7",
            },
            {
                id: 2,
                chromatic: 3,
                degree: "2",
                mode: "Dorian",
                chord: "m7",
            },
            {
                id: 3,
                chromatic: 5,
                degree: "3",
                mode: "Phrygian",
                chord: "m7",
            },
            {
                id: 4,
                chromatic: 6,
                degree: "4",
                mode: "Lydian",
                chord: "maj7",
            },
            {
                id: 5,
                chromatic: 8,
                degree: "5",
                mode: "Mixolydian",
                chord: "7",
            },
            {
                id: 6,
                chromatic: 10,
                degree: "6",
                mode: "Aeolian (Natural Minor)",
                chord: "m7",
            },
            {
                id: 7,
                chromatic: 12,
                degree: "7",
                mode: "Locrian",
                chord: "m7b5",
            },
        ],
    },
    {
        id: 2,
        name: "Melodic Minor",
        slug: "melodic-minor",
        formula: [
            {
                chromatic: 1,
                id: 1,
                degree: "1",
                mode: "Melodic minor",
                chord: "mMaj7",
            },
            {
                chromatic: 3,
                id: 2,
                degree: "2",
                mode: "Dorian b2 (or Prhygian ♮6)",
                chord: "m7",
            },
            {
                chromatic: 4,
                id: 3,
                degree: "b3",
                mode: "Lydian augmented (Lydian #5)",
                chord: "Maj7#5",
            },
            {
                chromatic: 6,
                id: 4,
                degree: "4",
                mode: "Lydian dominant",
                chord: "7",
            },
            {
                chromatic: 8,
                id: 5,
                degree: "5",
                mode: "Mixolydian b6",
                chord: "7",
            },
            {
                chromatic: 10,
                id: 6,
                degree: "6",
                mode: "Locrian ♮2 (Aeolocrian)",
                chord: "m7b5",
            },
            {
                chromatic: 12,
                id: 7,
                degree: "7",
                mode: "Super Locrian (Altered scale)",
                chord: "m7b5",
            },
        ],
    },
    {
        id: 3,
        name: "Harmonic Minor",
        slug: "harmonic-minor",
        formula: [
            {
                chromatic: 1,
                id: 1,
                degree: "1",
                mode: "Harmonic minor",
                chord: "mMaj7",
            },
            {
                chromatic: 3,
                id: 2,
                degree: "2",
                mode: "Locrian 13 (or Locrian natural 6th)",
                chord: "m7b5",
            },
            {
                chromatic: 4,
                id: 3,
                degree: "b3",
                mode: "Major #5",
                chord: "Maj7#5",
            },
            {
                chromatic: 6,
                id: 4,
                degree: "4",
                mode: "Dorian #4",
                chord: "m7",
            },
            {
                chromatic: 8,
                id: 5,
                degree: "5",
                mode: "Phrygian dominant",
                chord: "7",
            },
            {
                chromatic: 9,
                id: 6,
                degree: "b6",
                mode: "Lydian #2",
                chord: "maj7",
            },
            {
                chromatic: 12,
                id: 7,
                degree: "7",
                mode: "Super Locrian bb7",
                chord: "dim7",
            },
        ],
    },
    {
        id: 4,
        name: "Harmonic Major",
        slug: "harmonic-major",
        formula: [
            {
                chromatic: 1,
                id: 1,
                degree: "1",
                mode: "Harmonic major",
                chord: "maj7",
            },
            {
                chromatic: 3,
                id: 2,
                degree: "2",
                mode: "Dorian b5",
                chord: "m7b5",
            },
            {
                chromatic: 5,
                id: 3,
                degree: "3",
                mode: "Phrygian b4",
                chord: "m7",
            },
            {
                chromatic: 6,
                id: 4,
                degree: "4",
                mode: "Lydian b3",
                chord: "mMaj7",
            },
            {
                chromatic: 8,
                id: 5,
                degree: "5",
                mode: "Mixolydian b2",
                chord: "7",
            },
            {
                chromatic: 9,
                id: 6,
                degree: "b6",
                mode: "Lydian Augmented #2",
                chord: "Maj7#5",
            },
            {
                chromatic: 12,
                id: 7,
                degree: "7",
                mode: "Locrian bb7",
                chord: "dim7",
            },
        ],
    },
    {
        id: 5,
        name: "Diminished",
        slug: "diminished",
        formula: [
            {
                chromatic: 1,
                id: 1,
                degree: "1",
                mode: "Diminished (1)",
                chord: "dim7",
            },
            {
                chromatic: 3,
                id: 2,
                degree: "2",
                mode: "Inverted Diminished (2)",
                chord: "7",
            },
            {
                chromatic: 4,
                id: 3,
                degree: "b3",
                mode: "Diminished (3)",
                chord: "dim7",
            },
            {
                chromatic: 6,
                id: 4,
                degree: "4",
                mode: "Inverted Diminished (4)",
                chord: "7",
            },
            {
                chromatic: 7,
                id: 5,
                degree: "b5",
                mode: "Diminished (5)",
                chord: "dim7",
            },
            {
                chromatic: 9,
                id: 6,
                degree: "#5",
                mode: "Inverted Diminished (6)",
                chord: "7",
            },
            {
                chromatic: 10,
                id: 7,
                degree: "6",
                mode: "Diminished (7)",
                chord: "dim7",
            },
            {
                chromatic: 12,
                id: 8,
                degree: "7",
                mode: "Inverted Diminished (8)",
                chord: "7",
            },
        ],
    },
    {
        id: 6,
        name: "Augmented",
        slug: "augmented",
        formula: [
            {
                chromatic: 1,
                id: 1,
                degree: "1",
                mode: "Augmented (1)",
                chord: "maj7",
            },
            {
                chromatic: 4,
                id: 2,
                degree: "b3",
                mode: "Inverted Augmented (2)",
                chord: "6#5",
            },
            {
                chromatic: 5,
                id: 3,
                degree: "3",
                mode: "Augmented (3)",
                chord: "maj7",
            },
            {
                chromatic: 8,
                id: 4,
                degree: "5",
                mode: "Inverted Augmented (4)",
                chord: "6#5",
            },
            {
                chromatic: 9,
                id: 5,
                degree: "#5",
                mode: "Augmented (5)",
                chord: "maj7",
            },
            {
                chromatic: 12,
                id: 6,
                degree: "7",
                mode: "Inverted Augmented (6)",
                chord: "6#5",
            },
        ],
    },
    {
        id: 7,
        name: "Whole Tone",
        slug: "whole-tone",
        formula: [
            {
                chromatic: 1,
                id: 1,
                degree: "1",
                mode: "Whole Tone (1)",
                chord: "7 b5/#5",
            },
            {
                chromatic: 3,
                id: 2,
                degree: "2",
                mode: "Whole Tone (1)",
                chord: "7 b5/#5",
            },
            {
                chromatic: 5,
                id: 3,
                degree: "3",
                mode: "Whole Tone (1)",
                chord: "7 b5/#5",
            },
            {
                chromatic: 7,
                id: 4,
                degree: "#4",
                mode: "Whole Tone (1)",
                chord: "7 b5/#5",
            },
            {
                chromatic: 9,
                id: 5,
                degree: "#5",
                mode: "Whole Tone (1)",
                chord: "7 b5/#5",
            },
            {
                chromatic: 11,
                id: 6,
                degree: "#6",
                mode: "Whole Tone (1)",
                chord: "7 b5/#5",
            },
        ],
    },
];

/* Flat Map of all the notes */
const scalesFlatMap = scales.flatMap((i) => i.slug);

export { scalesFlatMap, scales };
